[workspace]
members = ["vibe-server", "core"]
resolver = "2"

[workspace.dependencies]
eyre = { git = "https://github.com/thewh1teagle/eyre", branch = "feat/report-serialize-backtrace", features = [
	"serialize",
] }
serde_json = "1.0.111"
