[workspace]
members = [
    "vibe-server",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[dependencies]
# Workspace-wide dependencies can be specified here if needed

[target.'cfg(target_os = "linux")'.dependencies]
openssl = { version = "0.10.63", features = ["vendored"] }
