[package]
name = "vibe"
version = "0.0.6"
description = "Vibe"
authors = ["@thewh1teagle"]
license = "MIT"
repository = "https://github.com/thewh1teagle/vibe"
edition = "2024"

[dependencies]
# Add these server-specific dependencies
axum = "0.7.5"
tower-http = { version = "0.5.0", features = ["cors"] }

tokio = { version = "1.35.1", features = ["net"] }
once_cell = "1.19.0"
env_logger = "0.10.1"
serde = { version = "^1.0.198", features = ["derive"] }
serde_json = { workspace = true }
eyre = { workspace = true }
url = "2.5.0"
open = "5.1.3"
showfile = "0.1.1"
clap = { version = "4.5.4", features = ["derive", "string"] }
futures = "0.3.30"
cpal = "0.15.3"
hound = "3.5.1"
rand = "0.8.5"
utoipa = { version = "4.2.3", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "7.1.0", features = ["axum"] }
tracing = { version = "0.1.40", features = ["log"] }
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json"] }
chrono = "0.4.38"
crash-handler = "0.6.2"
urlencoding = "2.1.3"


# Linux
[target.'cfg(target_os = "linux")'.dependencies]
vibe_core = { path = "../../core", features = [] }
openssl = { version = "0.10.63", features = ["vendored"] }

# Windows
[target.'cfg(windows)'.dependencies]
vibe_core = { path = "../../core", features = [] }
winreg = "0.52.0"
# Used to attach to console
windows = { version = "0.56.0", features = [
	"Win32_System_Console",
	"Win32_Foundation",
] }
# Used to redirect stdout/stderr from c++ to the attached console. otherwise whisper errors won't show
libc = "0.2.158"
libc-stdhandle = "0.1.0"


# macOS
[target.'cfg(target_os = "macos")'.dependencies]
vibe_core = { path = "../../core", features = ["coreml", "metal"] }
cocoa = "0.25.0"
screencapturekit = { version = "0.2.8", features = ["ci"] }
screencapturekit-sys = "0.2.8"
objc_id = "0.1"
core-graphics-helmer-fork = "0.24.0"

[features]
default = ["custom-protocol"]
cuda = ["vibe_core/cuda"]
coreml = ["vibe_core/coreml"]
metal = ["vibe_core/metal"]
openblas = ["vibe_core/openblas"]
rocm = ["vibe_core/rocm"]
vulkan = ["vibe_core/vulkan"]

# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
