name: Release

on:
    workflow_dispatch:

jobs:
    publish-tauri:
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                include:
                    - platform: "macos-latest" # for Arm based macs (M1 and above).
                      args: "--target aarch64-apple-darwin"
                    - platform: "debian-12"
                      args: '--features "vulkan"'
                      pre-build-args: "--vulkan"

        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@v4

            - name: setup Bun
              uses: oven-sh/setup-bun@v1

            - name: Rust cache
              uses: swatinem/rust-cache@v2

            - name: Install Rust stable
              uses: dtolnay/rust-toolchain@stable
              with:
                  # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
                  targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

            - name: Install frontend dependencies
              run: bun install
              working-directory: ./desktop

            - name: Prepare Vulkan SDK for Debian 12
              run: |
                  wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
                  echo "deb https://packages.lunarg.com/vulkan/1.3.290 bookworm main" | sudo tee /etc/apt/sources.list.d/lunarg-vulkan-1.3.290-bookworm.list
                  sudo apt update
                  sudo apt install vulkan-sdk -y
                  sudo apt-get install -y mesa-vulkan-drivers
              if: ${{ matrix.platform == 'debian-12' && contains(matrix.args, 'vulkan') }}

            # Run pre build
            - name: Run pre_build.js on ${{ matrix.platform }}
              run: bun scripts/pre_build.js ${{ matrix.pre-build-args }}

            - name: Build
              uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
                  TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
              with:
                  tagName: v__VERSION__ # the action automatically replaces __VERSION__ with the app version.
                  releaseName: "v__VERSION__"
                  releaseBody: "What's new? 🎉📣"
                  prerelease: true
                  args: ${{ matrix.args }}
                  projectPath: "./desktop"
                  tauriScript: bunx tauri
