name: Release macOS

'on':
  push:
    tags:
      - v*
  workflow_dispatch:

    null
jobs:
  publish-tauri-macos:
    permissions:
      contents: write
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Rust cache
        uses: swatinem/rust-cache@v2

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin,x86_64-apple-darwin

      - name: Install frontend dependencies
        run: bun install
        working-directory: ./desktop

      # Run pre build
      - name: Run pre_build.js on macOS
        run: bun scripts/pre_build.js

      - name: Build
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: v__VERSION__ # the action automatically replaces __VERSION__ with the app version.
          releaseName: v__VERSION__
          releaseBody: What's new? 🎉📣
          prerelease: true
          args: '--target aarch64-apple-darwin'
          projectPath: ./desktop
          tauriScript: bunx tauri